services:
  file_converter:
    container_name: file_converter
    build:
      context: src/external/services/converter
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network

  tonality_analysis:
    container_name: tonality_analysis
    build:
      context: src/external/services/analyser
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8030:8030"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge