"""Added s3_key field for File model

Revision ID: 10cbc49843d0
Revises: 97128a6d7e70
Create Date: 2025-01-30 16:10:31.769588

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10cbc49843d0"
down_revision: Union[str, None] = "97128a6d7e70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("s3_key", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "s3_key")
    # ### end Alembic commands ###
