"""2FA

Revision ID: 8b2944e758a3
Revises: 10cbc49843d0
Create Date: 2025-01-31 12:01:28.786748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b2944e758a3"
down_revision: Union[str, None] = "10cbc49843d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("totp_secret", sa.String(), nullable=True))
    op.add_column("users", sa.Column("is_2fa_enabled", sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, "users", ["totp_secret"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "is_2fa_enabled")
    op.drop_column("users", "totp_secret")
    # ### end Alembic commands ###
